#!/usr/bin/env python3
"""Regenerate src/data/habitats_vanilla.h.

Layer 1 of the randomizer's habitat classifier (docs/overhaul/ROADMAP.md 7.12
rule 1): the habitats a species belongs to because Emerald itself places it
there. Crosses src/data/wild_encounters.json with the hand-authored map tags in
src/data/habitats.h, so there is exactly one copy of the map->habitat mapping
and this file can never disagree with it.

Run after editing either input:

    python3 tools/overhaul/gen_habitats.py

test/habitat.c re-derives the same thing at runtime from the live encounter
tables and fails if the generated file has gone stale, so forgetting to run this
is caught by `make check TESTS="Habitat"` rather than shipping silently.
"""
import collections
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ENCOUNTERS = os.path.join(REPO, "src/data/wild_encounters.json")
MAP_TAGS = os.path.join(REPO, "src/data/habitats.h")
OUT = os.path.join(REPO, "src/data/habitats_vanilla.h")

# Rows of sAreaHabitats: { MAP_X, <land mask>, <water mask> },
ROW = re.compile(r"^\s*\{\s*(MAP_[A-Z0-9_]+),\s*(.+?),\s*(.+?)\s*\},\s*$", re.M)

# land and rock smash read the land mask; water and fishing read the water mask
AREA_FIELD = {"land": 1, "rock_smash": 1, "water": 2, "fishing": 2}


def parse_map_tags():
    text = open(MAP_TAGS, encoding="utf-8").read()
    tags = {m.group(1): (m.group(2).strip(), m.group(3).strip())
            for m in ROW.finditer(text)}
    if not tags:
        sys.exit("no map rows parsed from %s -- has the table format changed?" % MAP_TAGS)
    return tags


def expand(expr):
    """C mask expression -> set of HABITAT_* names.

    The bare `SEA_` shorthand has to be matched on a word boundary; a plain
    string replace also eats the SEA_ inside HABITAT_SEA_SURFACE and silently
    emits nonsense like HABITAT_HABITAT_SEA_SURFACE.
    """
    expr = re.sub(r"(?<![A-Z_])SEA_(?![A-Z])",
                  "HABITAT_SEA_SURFACE | HABITAT_SEA", expr)
    names = set(re.findall(r"HABITAT_[A-Z_]+", expr))
    unknown = {n for n in names if n == "HABITAT_HABITAT_SEA_SURFACE"}
    if unknown:
        sys.exit("mask expansion produced %s -- expand() is broken" % unknown)
    names.discard("HABITAT_NONE")
    return names


def collect_species():
    """{MAP_X: {area: [species, ...]}} for gWildMonHeaders."""
    data = json.load(open(ENCOUNTERS, encoding="utf-8"))
    group = next(g for g in data["wild_encounter_groups"]
                 if g["label"] == "gWildMonHeaders")
    out = collections.defaultdict(lambda: collections.defaultdict(list))
    for header in group["encounters"]:
        for key, table in header.items():
            if not key.endswith("_mons"):
                continue
            # One header per time of day, so accumulate: assigning would let the
            # last header win and drop the other times' species.
            out[header["map"]][key[:-5]] += [m["species"] for m in table["mons"]]
    return out


def main():
    tags = parse_map_tags()
    by_map = collect_species()

    habitats = collections.defaultdict(set)
    covered = skipped = 0
    for map_const, tables in by_map.items():
        if map_const not in tags:
            skipped += 1          # Kanto/Sevii: never reached in this hack
            continue
        covered += 1
        for area, species in tables.items():
            if area not in AREA_FIELD:
                sys.exit("unknown encounter area %r on %s" % (area, map_const))
            names = expand(tags[map_const][AREA_FIELD[area] - 1])
            if area == "rock_smash":
                names |= {"HABITAT_CAVE"}
            for s in species:
                habitats[s] |= names

    untagged = [m for m in tags if m not in by_map]
    if untagged:
        sys.exit("tagged maps with no encounter data: %s" % sorted(untagged))

    rows = "\n".join("    { %-34s %s }," % (s + ",", " | ".join(sorted(habitats[s])))
                     for s in sorted(habitats))

    open(OUT, "w", encoding="utf-8").write(
        "// Generated by tools/overhaul/gen_habitats.py -- do not hand-edit.\n"
        "//\n"
        "// Layer 1 of the habitat classifier (ROADMAP 7.12 rule 1): the habitats a\n"
        "// species belongs to because Emerald itself places it there. This is what puts\n"
        "// Zubat, Whismur and Makuhita in caves -- their typing alone would put them on\n"
        "// mountains and in fields. src/habitat.c ORs these bits on top of the\n"
        "// type/egg-group rules, and test/habitat.c fails if this file has gone stale.\n"
        "\n"
        "struct VanillaHabitat\n"
        "{\n"
        "    u16 species;\n"
        "    u16 habitats;\n"
        "};\n"
        "\n"
        "static const struct VanillaHabitat sVanillaHabitats[] =\n"
        "{\n%s\n};\n" % rows)

    print("maps tagged and used : %d" % covered)
    print("maps skipped (Kanto) : %d" % skipped)
    print("species classified   : %d" % len(habitats))
    print("wrote %s" % os.path.relpath(OUT, REPO))


if __name__ == "__main__":
    main()
